version: 2

formats: all

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc

build:
  os: ubuntu-22.04
  apt_packages:
    - swig
    - liblgpio1
  tools:
    python: "3"
